### ISSUE TITLE
Player can't load

### ISSUE THREAD

**Issue by nuzzzen** [kylon/Sharedown#31] opened 2022-03-22 17:01 UTC
Having this issue since forever, but I cannot understand if it's related to me or the application.
Every time sharedown completes the autologin correctly, it goes to the video URL and then chromium returns the following error:

![sharedown](https://user-images.githubusercontent.com/39726534/159534876-b8bcb1c8-a1c6-4bd5-a546-aa3b0400d1f8.jpeg)

So while working, I always have to get back to the chromium istance to reload the page, and then suddenly the download starts.
I don't know if this is the way Sharedown actually works, but if there's a way to _full automatize_ the download process, it would be perfect.

My system infos:

```
OS: Arch Linux x86_64
Kernel: 5.16.15-zen1-1-zen
CPU: Intel i7-9700K (8) @ 4.900GHz
GPU: NVIDIA GeForce GTX 1060 6GB
RAM: 16GB
```

Sharedown was installed from the AUR and this error happens using both FFmpeg or yt-dlp .
Let me know if you need logs or something else.

**Comment by kylon** [comment] 2022-03-25 13:11
the player does not load in puppeteer and it is not needed

correct behaviour is chromium will close itself and download starts, no manual refresh required.
for some reason it waits forever in your case

yes, post a log, even if i'm not sure there will be something useful

**Comment by nuzzzen** [comment] 2022-03-25 13:25
yt-dlp.log relevant logs (removed all the download progress lines)
```
[generic] videomanifest?provider=spo&inputFormat=mp4&cs=fFNQTw&docid=[huge-link-here]: Requesting header
[generic] videomanifest?provider=spo&inputFormat=mp4&cs=fFNQTw&docid=[huge-link-here]: Downloading webpage
[generic] videomanifest?provider=spo&inputFormat=mp4&cs=fFNQTw&docid=[huge-link-here]: Extracting information
[info] videomanifest?provider=spo&inputFormat=mp4&cs=fFNQTw&docid=[huge-link-here]: Downloading 1 format(s): vcopy+audcopy
[dashsegments] Total fragments: 298
[download] Destination: /[redacted].fvcopy.mp4

.
.
.

[debug] Command-line config: ['--no-part', '-N', '5', '-o', '[huge link]']
[debug] Encodings: locale UTF-8, fs utf-8, out utf-8 (No ANSI), err utf-8 (No ANSI), pref UTF-8
[debug] yt-dlp version 2022.03.08.1 [c0c2c57d3]
[debug] Python version 3.10.2 (CPython 64bit) - Linux-5.16.16-zen1-1-zen-x86_64-with-glibc2.35
[debug] exe versions: ffmpeg 5.0 (setts), ffprobe 5.0
[debug] Optional libraries: Cryptodome, mutagen, sqlite
[debug] Proxy map: {}
[debug] [generic] Extracting URL: [huge link]
WARNING: [generic] Falling back on generic information extractor.
[debug] Identified a DASH manifest
[debug] Formats sorted by: hasvid, ie_pref, lang, quality, res, fps, hdr:12(7), vcodec:vp9.2(10), acodec, filesize, fs_approx, tbr, vbr, abr, asr, proto, vext, aext, hasaud, source, id
[debug] Default format spec: bestvideo*+bestaudio/best
[debug] Invoking downloader on "huge link"
WARNING: The download speed shown is only of one thread. This is a known issue and patches are welcome

```

sharedownLog.log
```

_makeVideoManifestFetchURL: manifest template: {.mediaBaseUrl}/transform/videomanifest?provider=spo&inputFormat={.fileType}&cs={.callerStack}&docid={.spItemUrl}&{.driveAccessToken}


_makeVideoManifestFetchURL:
url:huge url

resp dump:
{"wpq":"","Templates":{},"ListData":{"Row":[],"FirstRow":1,"FolderPermissions":"0x1003008031001","LastRow":0,"RowLimit":30,"FilterLink":"?RootFolder=%2Fsites%2FAA2122%2DGEOMETRIAECOMBINATORIA%2D20810098%2DCANALE2SAMA%2FDocumenti%20condivisi%2FPrimo%20Modulo%2FRecordings%2FSolo%20visualizzazione%2FPrimo%20Modulo%20%28Salvitti%29%2D20211007%5F161945%2DRegistrazione%20della%20riunione%2Emp4&","ForceNoHierarchy":"1","HierarchyHasIndention":"","FolderId":"15","CurrentFolderProgId":"Media.Meeting","CurrentFolderUniqueId":"dfa5da38-69cc-403f-9863-2bd0e92b6f24","CurrentFolderSpItemUrl":"https://uniroma3.sharepoint.com:443/_api/v2.0/drives/b!cRAdVS6wGUqVrMFo1-bvk4EuHZChzmJDif8At1LqfrMmdzs46f3pQ7EzJBLSenpo/items/01AD4PQWBY3KS57TDJH5AJQYZL2DUSW3ZE?version=Published"},"ListSchema":{"Field":[],"RequiredFields":[],"LCID":"1033","Userid":"284","PagePath":"","ShowWebPart":"","View":"{F3EAB29F-4013-4C72-BFF5-8253DFF46037}","RootFolderParam":"View={f3eab29f-4013-4c72-bff5-8253dff46037}&RootFolder=%2Fsites%2FAA2122%2DGEOMETRIAECOMBINATORIA%2D20810098%2DCANALE2SAMA%2FDocumenti%20condivisi%2FPrimo%20Modulo%2FRecordings%2FSolo%20visualizzazione%2FPrimo%20Modulo%20%28Salvitti%29%2D20211007%5F161945%2DRegistrazione%20della%20riunione%2Emp4&","FieldSortParam":"","HttpVDir":"https://uniroma3.sharepoint.com/sites/AA2122-GEOMETRIAECOMBINATORIA-20810098-CANALE2SAMA","IsDocLib":"1","DefaultItemOpen":"1","ForceCheckout":"0","Direction":"none","TabularView":"1","ItemCount":"79","Locale":"it-IT","ReadOnlyUI":"False","Toolbar":"Standard",".driveAccessToken":"<hidden>",".driveUrl":"https://uniroma3.sharepoint.com/_api/v2.0/drives/b!cRAdVS6wGUqVrMFo1-bvk4EuHZChzmJDif8At1LqfrMmdzs46f3pQ7EzJBLSenpo",".driveAccessTokenV21":"<hidden>",".driveUrlV21":"https://uniroma3.sharepoint.com/_api/v2.1/drives/b!cRAdVS6wGUqVrMFo1-bvk4EuHZChzmJDif8At1LqfrMmdzs46f3pQ7EzJBLSenpo",".mediaBaseUrl":"https://westeurope1-mediap.svc.ms",".mediaBaseUrlSecondary":"https://northeurope1-mediap.svc.ms",".pushChannelBaseUrl":"https://westeurope0-pushnp.svc.ms",".callerStack":"fFNQTw",".correlationId":"43362da0-c0c5-4000-2e36-8c9030392a30",".transformUrl":"{.mediaBaseUrl}/transform/{.method}?provider=spo&inputFormat={.fileType}&cs={.callerStack}&docid={.spItemUrl}&{.driveAccessToken}",".thumbnailUrl":"{.mediaBaseUrl}/transform/thumbnail?provider=spo&inputFormat={.fileType}&cs={.callerStack}&docid={.spItemUrl}&{.driveAccessToken}",".videoManifestUrl":"{.mediaBaseUrl}/transform/videomanifest?provider=spo&inputFormat={.fileType}&cs={.callerStack}&docid={.spItemUrl}&{.driveAccessToken}",".pdfConversionUrl":"{.mediaBaseUrl}/transform/pdf?provider=spo&inputFormat={.fileType}&cs={.callerStack}&docid={.spItemUrl}&{.driveAccessToken}",".officeBundleGenerate":"{.mediaBaseUrl}/transform/OfficeBundle?provider=spo&inputFormat={.fileType}&cs={.callerStack}&docid={.spItemUrl}&{.driveAccessToken}",".officeBundleGetFragment":"{.mediaBaseUrl}/transform/OfficeBundleFragment?provider=spo&inputFormat={.fileType}&cs={.callerStack}&docid={.spItemUrl}&{.driveAccessToken}","ReadSecurity":"1"},"EnableAttachments":"false","BaseViewID":"1","ListTemplateType":"101","listBaseType":1,"noGroupCollapse":true,"InlineEdit":false,"ModernListTemplateTypeId":"","Flags2":229392,"checkPowerAppState":false,"tick":637838109072910600,"MachineLearningCaptureEnabled":false,"AIBuilderEnabled":false,"MachineLearningExperienceEnabled":true,"NavigateForFormsPages":true,"BasePermissions":{"ManageLists":true,"ManagePersonalViews":true,"OpenItems":true,"UseClientIntegration":true},"ListPermissions":"1b03c431aef","CreatedFromExcel":false,"CreatedFromExisting":false,"CurrentUserIsSiteAdmin":false,"IsAppWeb":false,"AllowGridMode":true,"inGridMode":false,"listTemplate":"101","listName":"{383B7726-FDE9-43E9-B133-2412D27A7A68}","rootFolder":"/sites/AA2122-GEOMETRIAECOMBINATORIA-20810098-CANALE2SAMA/Documenti condivisi/Primo Modulo/Recordings/Solo visualizzazione/Primo Modulo (Salvitti)-20211007_161945-Registrazione della riunione.mp4","view":"{F3EAB29F-4013-4C72-BFF5-8253DFF46037}","viewTitle":"All Documents","listUrlDir":"/sites/AA2122-GEOMETRIAECOMBINATORIA-20810098-CANALE2SAMA/Documenti%20condivisi","HttpPath":"https://uniroma3.sharepoint.com/sites/AA2122-GEOMETRIAECOMBINATORIA-20810098-CANALE2SAMA/_vti_bin/owssvr.dll?CS=65001","HttpRoot":"https://uniroma3.sharepoint.com/sites/AA2122-GEOMETRIAECOMBINATORIA-20810098-CANALE2SAMA","WebUrl":"https://uniroma3.sharepoint.com/sites/AA2122-GEOMETRIAECOMBINATORIA-20810098-CANALE2SAMA","ListUrl":"/sites/AA2122-GEOMETRIAECOMBINATORIA-20810098-CANALE2SAMA/Documenti condivisi","NoScriptEnabled":true,"imagesPath":"https://uniroma3.sharepoint.com/sites/AA2122-GEOMETRIAECOMBINATORIA-20810098-CANALE2SAMA/_layouts/15/images/","PortalUrl":null,"SendToLocationName":"","SendToLocationUrl":"","RecycleBinEnabled":1,"OfficialFileName":"","OfficialFileNames":"","WriteSecurity":"1","SiteTitle":"AA21/22 - GEOMETRIA E COMBINATORIA - 20810098 - CANALE 2 (SAMA')","ListTitle":"Documents","displayFormUrl":"https://uniroma3.sharepoint.com/sites/AA2122-GEOMETRIAECOMBINATORIA-20810098-CANALE2SAMA/_layouts/15/listform.aspx?PageType=4&ListId=%7B383B7726%2DFDE9%2D43E9%2DB133%2D2412D27A7A68%7D","newFormUrl":"https://uniroma3.sharepoint.com/sites/AA2122-GEOMETRIAECOMBINATORIA-20810098-CANALE2SAMA/_layouts/15/listform.aspx?PageType=8&ListId=%7B383B7726%2DFDE9%2D43E9%2DB133%2D2412D27A7A68%7D&RootFolder=%2Fsites%2FAA2122%2DGEOMETRIAECOMBINATORIA%2D20810098%2DCANALE2SAMA%2FDocumenti%20condivisi%2FPrimo%20Modulo%2FRecordings%2FSolo%20visualizzazione%2FPrimo%20Modulo%20%28Salvitti%29%2D20211007%5F161945%2DRegistrazione%20della%20riunione%2Emp4","editFormUrl":"https://uniroma3.sharepoint.com/sites/AA2122-GEOMETRIAECOMBINATORIA-20810098-CANALE2SAMA/_layouts/15/listform.aspx?PageType=6&ListId=%7B383B7726%2DFDE9%2D43E9%2DB133%2D2412D27A7A68%7D","CurrentUserId":284,"isModerated":false,"EnableRequestSignOff":true,"isForceCheckout":false,"EnableMinorVersions":false,"verEnabled":true,"recursiveView":false,"WorkflowsAssociated":false,"ContentTypesEnabled":false,"DocumentLibraryCalloutOfficeWebAppPreviewersDisabled":false,"RegionalSettingsTimeZoneBias":-60,"NewWOPIDocumentEnabled":false,"NewWOPIDocumentTypes":318,"canUserCreateMicrosoftForm":true,"AllowCreateFolder":true,"CanShareLinkForNewDocument":false,"VisioDrawingCreationEnabled":false,"SiteTemplateId":64,"TenantTagPolicyEnabled":false,"WebExcludeFromOfflineClient":false,"ExcludeFromOfflineClient":false}


_getFileName:
docid: huge url

url: huge url



```

**Comment by kylon** [comment] 2022-03-25 13:46
nothing wrong in log, can you try latest sharedown version, just in case it was some weirdness in puppeteer

if the problem is still there, i ll pack a test version

**Comment by nuzzzen** [comment] 2022-03-25 13:54
The issue manifested since the beginning, updates never fixed this.
I have reason to think this is related to my Uni connection with sharepoint, because a friend of mine tried the latest version (OSX) of SD and got the same issue. 

I'd have to try and change something in the source code in order to make the puppeteer reload the page after it's loaded, maybe this will remove the hassle to reload everytime. I'm not really familiar with JS but I can try and maybe create a fork.

Thank you for your fast reply, have a nice day my friend.

**Comment by kylon** [comment] 2022-03-25 14:15
ah, well, in this case, yes, it is something specific to your university

i suspect it is stuck here
https://github.com/kylon/Sharedown/blob/325285652dde5257f614de9309fa8bd81b888bef/preload.js#L573

**Comment by kylon** [comment] 2022-05-06 12:34
i can attach test versions and see if we can find what's wrong if you want.

nothing should be changed for yt-dlp, errors?
i noticed latest yt-dlp release takes some more time to start the download, but thats it

**Comment by nuzzzen** [comment] 2022-05-06 12:55
I'd be happy to work with you to solve this problem, as this would also help my fellow Uni colleagues!

Regarding **yt-dlp:** I tried running the latest version on a MacBook Pro (M1), all goes fine (the previous "player can't load" error remains tho). I'll try on Windows 10 and see if it works. 

You can DM me on Discord at `ŋuzzzeŋ#7821`.

**Closed** 2022-05-15 16:19 UTC

**Comment by markcs** [comment] 2022-05-19 13:13
Sorry to ask in a closed issue, but what was the fix for this?

Thanks

**Comment by kylon** [comment] 2022-05-19 13:20
the fix is included in 4.2

**Comment by markcs** [comment] 2022-05-19 13:45
> the fix is included in 4.2

I have the same issue with 4.2 portable on windows

**Comment by markcs** [comment] 2022-05-19 13:55
> what kind of issue

The _Player can't load_ problem reported in this issue

**Comment by kylon** [comment] 2022-05-19 13:58
the player will not load, this is correct, not an error
