### ISSUE TITLE
new versions don't work

### ISSUE THREAD

**Issue by ppfans** [kylon/Sharedown#60] opened 2022-12-16 07:21 UTC
I used Sharedown for a long time. Thanks to Kylon of the great job!
Recently I found it not work any more after the version of 5.0.2. I tried version 5.1, 5.2.1, 5.2.2, and they do not jump back to Sharedown for download. While version 5.0.2 and before still work.

Log:
```
startDownload: start

startDownload: valid data: true

runPuppeteerGetVideoData: goto https://mdigital-my.sharepoint.com/***

_sharepointLogin: start login procedure

_waitForVideoPlayer: ignore:
Execution context was destroyed, most likely because of a navigation.

_waitForVideoPlayer: ignore:
Execution context was destroyed, most likely because of a navigation.

_waitForVideoPlayer: ignore:
JSHandles can be evaluated only in the context they were created!

_waitForVideoPlayer: ignore:
JSHandles can be evaluated only in the context they were created!

_waitForVideoPlayer: ignore:
JSHandles can be evaluated only in the context they were created!

_waitForVideoPlayer: ignore:
JSHandles can be evaluated only in the context they were created!

_waitForVideoPlayer: ignore:
JSHandles can be evaluated only in the context they were created!

_waitForVideoPlayer: ignore:
JSHandles can be evaluated only in the context they were created!

_waitForVideoPlayer: ignore:
JSHandles can be evaluated only in the context they were created!

_waitForVideoPlayer: ignore:
JSHandles can be evaluated only in the context they were created!

_waitForVideoPlayer: ignore:
JSHandles can be evaluated only in the context they were created!

_waitForVideoPlayer: ignore:
JSHandles can be evaluated only in the context they were created!

```

**Comment by kylon** [comment] 2022-12-16 07:53
so, 5.0.2 is working, 5.1.0 is not working?

**Comment by ppfans** [comment] 2022-12-19 13:51
Sorry, I'm confused. It seems 5.22 work today. I tested every version when lauched from 5.1 to 5.22 to see if it fixed. non of these worked, but 5.02 always working. Every time browser will idle on the page of "Player can't load".
But today 5.22 worked! I will continue do the test and let you know if there is any progress.

**Comment by Elvino00** [comment] 2022-12-23 09:50
> Sorry, I'm confused. It seems 5.22 work today. I tested every version when lauched from 5.1 to 5.22 to see if it fixed. non of these worked, but 5.02 always working. Every time browser will idle on the page of "Player can't load". But today 5.22 worked! I will continue do the test and let you know if there is any progress.

It's normal for the browser to say "player can't load" but the downloads actually are going on.

**Comment by kylon** [comment] 2022-12-23 09:52
yes, this is how it works

**Comment by ppfans** [comment] 2022-12-23 11:33
Yes, I know. But it will stay on the page of "player can't load" permanantly. I set the timeout to 99999, because I need additional time from input and verification for sharepoint. When I close the web page, the software is still circle, it will not prompt error as usual. But the version 5.02 is normal. I tried several times, and this issue still happened for verision from 5.1 to 5.22.

**Comment by kylon** [comment] 2022-12-24 09:17
you can set 0 to disable the timeout

the only big change in 5.1 is puppeteer upgrade from 17 to 19, if 5.1 is the first one that breaks for you, then this sounds like a puppeteer regression

[Sharedownt.zip](https://github.com/kylon/Sharedown/files/10298282/Sharedownt.zip)
this is 5.0.2 with puppeteer 18.0

**Comment by ppfans** [comment] 2022-12-29 01:26
Sorry, there is no executive file in it. I can only run the portable version.

**Comment by Elvino00** [comment] 2022-12-29 09:26
> Sorry, there is no executive file in it. I can only run the portable version.

1) Extract the content of the archive
2) Enter in the folder created after the extraction and open a terminal
3) write "npm i" or "yarn install"
4) write "npm start" (in case it didn't work use "npm run" ) if you used "npm i" or "yarn run" (or "yarn start", i don't remember) if you used "yarn install"

**Comment by ppfans** [comment] 2023-02-10 03:27
both versions do not work now.
when I use build in chromium, it shows
"Something went wrong
Either your current settings or your browser is not supported or outdated. Use a different browser and try again."
If I change to chrome. It will start play video, but cannot download.

**Comment by kylon** [comment] 2023-02-10 21:27
weird message, i will update chromium and post to test
if it gets stuck press f5 to reload the page and it should start, something when 2fa or too many redirects happens

**Comment by kylon** [comment] 2023-02-14 15:46
[Sharedownt.zip](https://github.com/kylon/Sharedown/files/10734186/Sharedownt.zip)

try with this

same instruction: https://github.com/kylon/Sharedown/issues/60#issuecomment-1367184483

**Comment by dj9364** [comment] 2023-02-15 09:41
> [Sharedownt.zip](https://github.com/kylon/Sharedown/files/10734186/Sharedownt.zip)
> 
> try with this
> 
> same instruction: [#60 (comment)](https://github.com/kylon/Sharedown/issues/60#issuecomment-1367184483)

I had the same issue, "Either your current settings or your browser is not supported or outdated. Use a different browser and try again".
I've tried using a different browser, Chrome 109.0.5414.120 and Firefox 108.0.2, the video player starts but never goes back to sharedown (latest release). 

Now I've downloaded your Sharedownt.zip, built it and when I paste a sharedown link and press "start download", it shows "failed to find chrome executable". 

I've used the same settings with the same release, but in November/december worked flawlessly, now it give errors about using a different browser.

**Comment by kylon** [comment] 2023-02-15 10:31
build for what os? sounds like partial build

where do you see that message?

**Comment by StranaPatata** [comment] 2023-02-15 21:10
OS is Windows 10 22H2. Message appears after doing:

> Click "Add Sharepoint URLs"
> Paste link(s) in the white box
> Click "Save"
> Click "Start download"

As soon as I start the download, this error appears about puppeteer. 
![Screenshot 2023-02-15 220757](https://user-images.githubusercontent.com/34387921/219163031-1522e186-f1e0-4f9c-b546-b287e15c48da.png)

**Comment by kylon** [comment] 2023-02-16 08:36
sorry i mean the not supported browser message

are you using a system wide install? C:\Program Files
if yes, that error has been fixed in main, if no, the build failed to find/include puppeteer

**Comment by StranaPatata** [comment] 2023-02-16 12:38
The "Not supported browser or settings" error message appears after clicking "Start download".
Sharedown opens chromium and does everything according to automation (writing login details, clicking some buttons and so on), when the sharepoint webpage loads with the video player, it loads for a bit and then the player is covered by the error.

![Screenshot 2023-02-16 121526](https://user-images.githubusercontent.com/34387921/219351644-9578ea5d-a4e3-4bc5-ad22-328ac3f4ca3d.png)


After this, chromium self-closes because of "Navigation timeout of 2000ms exceeded".

This happens using the main (with the updated preload.js published yesterday) and launching it with the terminal using npm install and npm start. The software USUALLY fails to grab the stream and download it, sadly. I've tried with different links from different classes, also with links of known streams that in the past I was able to download so in my opinion, it's not related to the uploader's settings.

For each link, if I try a couple times, it starts the download even after showing the "Not supported browser or settings" error message, but this means that the queue is basically broken because even if I add different links, for every video I need to be present and manually click a couple of times the "start download" button, because chromium self closes and throws the error.

So the issue is not related to the specific link I input into Sharedown, because the same video that gives me errors, eventually starts downloading. 

Here is the log:
`startDownload: start

startDownload: valid data: true

runPuppeteerGetVideoData: goto https://.......[link to actual stream]

_sharepointLogin: start login procedure

_sharepointLogin: has login data

_sharepointLogin: has auto-login

_waitForVideoPlayer: ignore:
Execution context was destroyed, most likely because of a navigation.

_waitForVideoPlayer: ignore:
Execution context was destroyed, most likely because of a navigation.

runPuppeteerGetVideoData: error
Navigation timeout of 20000 ms exceeded

downloadVideo: has vdata: false

startDownload: failed
undefined`

This is the log for when it fails to grab the stream.

If I change the .exe from built-in chromium to my personal installation of Chrome, the recording actually plays and I can even stop it, speed it or toggle subtitles, but after that it closes automatically because of the timeout, without grabbing the stream.

Hopefully I've written enough information.

**Comment by kylon** [comment] 2023-02-16 13:41
ok ok, i think i will add a warning on download start about this (~finally~)

builtin chromium cannot play videos, the **something went wrong, etc..**, is telling you that
sharedown doesn't care about this and never will, ignore all player errors


now the actual issue

log is clean, i think increasing or disabling (probably better) the timeout is what you need
just
![2023-02-16-143527_221x85_scrot](https://user-images.githubusercontent.com/3252255/219380138-1c2162e2-5b68-41c7-a7a6-2ea8c6755886.png)
and save

this should solve your issue

**Comment by StranaPatata** [comment] 2023-02-16 19:11
Thanks a lot, first increasing the browser timeout and then disabling it seems to have fixed the issue. I wonder what MS changed that now Sharedown requires more time to obtain the stream link to download..
Anyway thanks again, I can finally finish to archive all the meetings that were left.

**Comment by kylon** [comment] 2023-04-02 14:45
closing this since now OT and new build is out
the other 2 issues mentioned have been solved, switched to zip format and no crash on stop

if you still have issues, please open a new one for latest release
thanks

**Closed by kylon** 2023-04-02 14:45 UTC
