### ISSUE TITLE
Builtin Chromium crashes on M1 Mac

### ISSUE THREAD

**Issue by KleaTech** [kylon/Sharedown#62] opened 2023-01-09 15:57 UTC
When I start the download, Chromium starts, I log in to Stream, it loads the page, player becomes visible for a moment then Chromium crashes. Sharedown shows error message about the browser crash and does not download the video.
[chromium log.txt](https://github.com/kylon/Sharedown/files/10374621/chromium.log.txt)

**Comment by kylon** [comment] 2023-01-09 20:35
don't have m1 mac right now, i can test in a few days

can you try with a different chrome/chromium? custom chrome executable in sharedown settings

**Comment by KleaTech** [comment] 2023-01-09 21:56
I tried with a Google Chrome app (installed from browser) that I regularly use. It said something on the line that it does not have permission to run it. I can experiment with it tomorrow, maybe try Edge too or check some permissions. Unfortunatelly I don't have much experience with Macs.

**Comment by kylon** [comment] 2023-02-10 21:33
borrowing a m1 is taking longer, i ll post an updated build to see if this is fixed upstream, not sure this is sharedown issue tho

**Comment by kylon** [comment] 2023-04-01 17:22
tested on macbook pro 18.3 2021, ventura 13.0

cannot reproduce any crash there with 5.2.2 release package or master

the only thing i found is that 5.2.2 arm64 release package does not run on ventura (fixed by building with latest builder)

**Comment by kylon** [comment] 2023-09-11 13:04
closing for inactivity

**Closed by kylon** 2023-09-11 13:04 UTC
